services:
  cloudflared:
    image: cloudflare/cloudflared:2026.1.2
    container_name: CptcEventsTunnel
    command: tunnel --no-autoupdate run --token ${TOKEN}
    restart: unless-stopped
    networks:
      - CptcEventsNetwork
  reverse-proxy:
    image: caddy:2.11-alpine
    container_name: CptcEventsProxy
    volumes:
        - ./proxy/Caddyfile:/etc/caddy/Caddyfile:ro
        - ./proxy/coldstart:/var/www/coldstart:ro
    restart: unless-stopped
    networks:
        - CptcEventsNetwork

networks:
  CptcEventsNetwork:
    internal: true
