services:
  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: CptcEventsTunnel
    volumes:
      - ./config:/etc/cloudflared
    command: tunnel --no-autoupdate run --token ${TOKEN}
    restart: unless-stopped
    networks:
      - CptcEventsNetwork
  reverse-proxy:
        image: caddy:alpine
        container_name: CptcEventsProxy
        volumes:
            - ./proxy/Caddyfile:/etc/caddy/Caddyfile:ro
            - ./proxy/coldstart:/var/www/coldstart:ro
        restart: unless-stopped
        networks:
            - CptcEventsNetwork

networks:
  CptcEventsNetwork:
    external: true
