ingress:
  - hostname: cptcevents.org
    service: http://CptcEventsProxy:80
    originRequest:
      connectTimeout: 30s
      noTLSVerify: true
  - hostname: www.cptcevents.org
    service: http://CptcEventsProxy:80
    originRequest:
      connectTimeout: 30s
      noTLSVerify: true

  # Default rule
  - service: http_status:404
